declare
   procedure drop_table (
      p_table_name varchar2
   ) is
   begin
      execute immediate 'DROP TABLE "'
                        || p_table_name
                        || '" CASCADE CONSTRAINTS';
   exception
      when others then
         if sqlcode != -942 then
            raise;
         end if;
   end;
begin
   drop_table('PAYMENT');
   drop_table('INVOICE');
   drop_table('LASER');
   drop_table('IMAGE_SESSION');
   drop_table('PRINT');
   drop_table('Order');
   drop_table('EMPLOYEE_SKILL');
   drop_table('EMPLOYEE_ROLE');
   drop_table('ATTENDANCE');
   drop_table('COUPON');
   drop_table('SKILL');
   drop_table('ROLE');
   drop_table('EMPLOYEE');
   drop_table('CUSTOMER');
   drop_table('PERSON');
end;
/






create table "PERSON" (
   "ID"          number generated by default as identity minvalue 1 maxvalue 9999999999999999999999999999 increment by 1 start
   with 1 cache 20 noorder nocycle nokeep noscale not null enable,
   "FIRST_NAME"  varchar2(30 byte) not null enable,
   "MIDDLE_NAME" varchar2(30 byte) not null enable,
   "LAST_NAME"   varchar2(30 byte) not null enable,
   "ADDRESS"     varchar2(60 byte) not null enable,
   "PHONE"       varchar2(10 byte) not null enable,
   "SEX"         char(1 byte) not null enable,
   "PERSON_TYPE" varchar2(20 byte)
)
segment creation immediate
pctfree 10
pctused 40
initrans 1
maxtrans 255 nocompress
logging
tablespace "USERS";

alter table "PERSON"
   add
      check ( sex in ( 'M',
                       'F' ) ) enable;
alter table "PERSON"
   add
      check ( person_type in ( 'CUSTOMER',
                               'EMPLOYEE' ) ) enable;
alter table "PERSON"
   add primary key ( "ID" )
      using index tablespace "USERS" enable;



create table "CUSTOMER" (
   "PERSON_ID" number
)
segment creation deferred
pctfree 10
pctused 40
initrans 1
maxtrans 255 nocompress
logging
tablespace "USERS";

alter table "CUSTOMER"
   add primary key ( "PERSON_ID" )
      using index tablespace "USERS" enable;



create table "EMPLOYEE" (
   "PERSON_ID"     number,
   "SALARY"        number(6,0) not null enable,
   "HIRE_DATE"     date not null enable,
   "USER_NAME"     varchar2(30 byte) not null enable,
   "USER_PASSWORD" varchar2(50 byte) not null enable,
   "EMP_TYPE"      varchar2(20 byte)
)
segment creation immediate
pctfree 10
pctused 40
initrans 1
maxtrans 255 nocompress
logging
tablespace "USERS";

alter table "EMPLOYEE"
   add
      check ( emp_type in ( 'MANAGER',
                            'PHOTOGRAPHER',
                            'RECEPTIONIST',
                            'OTHER' ) ) enable;
alter table "EMPLOYEE"
   add primary key ( "PERSON_ID" )
      using index tablespace "USERS" enable;
alter table "EMPLOYEE" add unique ( "USER_NAME" )
   using index tablespace "USERS" enable;
alter table "EMPLOYEE"
   add constraint "FK_EMPLOYEE_PERSON"
      foreign key ( "PERSON_ID" )
         references "PERSON" ( "ID" )
      enable;



create table "SKILL" (
   "ID"   number generated by default as identity minvalue 1 maxvalue 9999999999999999999999999999 increment by 1 start with 1
   cache 20 noorder nocycle nokeep noscale not null enable,
   "NAME" varchar2(50 byte) not null enable
)
segment creation immediate
pctfree 10
pctused 40
initrans 1
maxtrans 255 nocompress
logging
tablespace "USERS";

alter table "SKILL"
   add primary key ( "ID" )
      using index tablespace "USERS" enable;



create table "ROLE" (
   "ID"   number,
   "NAME" varchar2(20 byte) not null enable
)
segment creation immediate
pctfree 10
pctused 40
initrans 1
maxtrans 255 nocompress
logging
tablespace "USERS";

alter table "ROLE"
   add primary key ( "ID" )
      using index tablespace "USERS" enable;



create table "COUPON" (
   "ID"               number generated by default as identity minvalue 1 maxvalue 9999999999999999999999999999 increment by 1
   start with 1 cache 20 noorder nocycle nokeep noscale not null enable,
   "DISCOUNT_PERCENT" number(2,2) not null enable,
   "CODE"             varchar2(10 byte) not null enable,
   "STATUS"           number(1,0) not null enable,
   "NOTE"             varchar2(100 byte),
   "START_AT"         timestamp(6) not null enable,
   "END_AT"           timestamp(6) not null enable
)
segment creation immediate
pctfree 10
pctused 40
initrans 1
maxtrans 255 nocompress
logging
tablespace "USERS";

alter table "COUPON"
   add primary key ( "ID" )
      using index tablespace "USERS" enable;



create table "EMPLOYEE_SKILL" (
   "EMP_ID"   number,
   "SKILL_ID" number,
   "YEARS"    number not null enable
)
segment creation deferred
pctfree 10
pctused 40
initrans 1
maxtrans 255 nocompress
logging
tablespace "USERS";

alter table "EMPLOYEE_SKILL"
   add constraint "PK_EMP_SKILL"
      primary key ( "EMP_ID",
                    "SKILL_ID" )
         using index tablespace "USERS" enable;
alter table "EMPLOYEE_SKILL"
   add constraint "FK_ES_EMP"
      foreign key ( "EMP_ID" )
         references "EMPLOYEE" ( "PERSON_ID" )
      enable;
alter table "EMPLOYEE_SKILL"
   add constraint "FK_ES_SKILL"
      foreign key ( "SKILL_ID" )
         references "SKILL" ( "ID" )
      enable;



create table "EMPLOYEE_ROLE" (
   "EMP_ID"    number,
   "ROLE_ID"   number,
   "HIRE_DATE" date not null enable
)
segment creation immediate
pctfree 10
pctused 40
initrans 1
maxtrans 255 nocompress
logging
tablespace "USERS";

alter table "EMPLOYEE_ROLE"
   add constraint "PK_EMP_ROLE"
      primary key ( "EMP_ID",
                    "ROLE_ID" )
         using index tablespace "USERS" enable;
alter table "EMPLOYEE_ROLE"
   add constraint "FK_ER_ROLE"
      foreign key ( "ROLE_ID" )
         references "ROLE" ( "ID" )
      enable;



create table "ATTENDANCE" (
   "ID"        number generated by default as identity minvalue 1 maxvalue 9999999999999999999999999999 increment by 1 start with
   1 cache 20 noorder nocycle nokeep noscale not null enable,
   "EMP_ID"    number,
   "CHECK_IN"  timestamp(6) not null enable,
   "CHECK_OUT" timestamp(6) not null enable,
   "DATE"      date not null enable,
   "STATUS"    number(1,0) not null enable
)
segment creation immediate
pctfree 10
pctused 40
initrans 1
maxtrans 255 nocompress
logging
tablespace "USERS";

alter table "ATTENDANCE"
   add primary key ( "ID" )
      using index tablespace "USERS" enable;
alter table "ATTENDANCE"
   add constraint "FK_ATTENDANCE_EMP"
      foreign key ( "EMP_ID" )
         references "EMPLOYEE" ( "PERSON_ID" )
      enable;



create table "Order" (
   "ID"               number generated by default as identity minvalue 1 maxvalue 9999999999999999999999999999 increment by 1
   start with 1 cache 20 noorder nocycle nokeep noscale not null enable,
   "CUSTOMER_ID"      number,
   "RECEPTIONIST_ID"  number,
   "COUPON_ID"        number,
   "DISCOUNT_PERCENT" number(3,2) default 1.00,
   "START_AT"         timestamp(6) not null enable,
   "END_AT"           timestamp(6) not null enable,
   "ORDER_AT"         timestamp(6) not null enable,
   "STATUS"           number(1,0) not null enable,
   "PRICE"            number not null enable,
   "DESCRIPTION"      varchar2(200 byte),
   "ORDER_TYPE"       varchar2(30 byte)
)
segment creation immediate
pctfree 10
pctused 40
initrans 1
maxtrans 255 nocompress
logging
tablespace "USERS";

alter table "Order"
   add
      check ( order_type in ( 'IMAGE',
                              'PRINT',
                              'LASER' ) ) enable;
alter table "Order"
   add primary key ( "ID" )
      using index tablespace "USERS" enable;
alter table "Order"
   add constraint "FK_ORDER_CUST"
      foreign key ( "CUSTOMER_ID" )
         references "PERSON" ( "ID" )
      enable;
alter table "Order"
   add constraint "FK_ORDER_RECEP"
      foreign key ( "RECEPTIONIST_ID" )
         references "EMPLOYEE" ( "PERSON_ID" )
      enable;
alter table "Order"
   add constraint "FK_ORDER_COUP"
      foreign key ( "COUPON_ID" )
         references "COUPON" ( "ID" )
      enable;



create table "LASER" (
   "ORDER_ID"        number,
   "MATERIALS"       varchar2(20 byte) not null enable,
   "DESIGN_FILE_URL" varchar2(225 byte) not null enable
)
segment creation immediate
pctfree 10
pctused 40
initrans 1
maxtrans 255 nocompress
logging
tablespace "USERS";

alter table "LASER"
   add primary key ( "ORDER_ID" )
      using index tablespace "USERS" enable;
alter table "LASER"
   add constraint "FK_LASER_ORDER"
      foreign key ( "ORDER_ID" )
         references "Order" ( "ID" )
      enable;



create table "IMAGE_SESSION" (
   "ORDER_ID"        number,
   "SESSION_TYPE"    varchar2(15 byte) not null enable,
   "SCHEDULED_AT"    timestamp(6) not null enable,
   "DURATION"        number(3,0) not null enable,
   "PHOTOGRAPHER_ID" number
)
segment creation deferred
pctfree 10
pctused 40
initrans 1
maxtrans 255 nocompress
logging
tablespace "USERS";

alter table "IMAGE_SESSION"
   add primary key ( "ORDER_ID" )
      using index tablespace "USERS" enable;
alter table "IMAGE_SESSION"
   add constraint "FK_SESSION_ORDER"
      foreign key ( "ORDER_ID" )
         references "Order" ( "ID" )
      enable;
alter table "IMAGE_SESSION"
   add constraint "FK_SESSION_PHOTO"
      foreign key ( "PHOTOGRAPHER_ID" )
         references "EMPLOYEE" ( "PERSON_ID" )
      enable;



create table "PRINT" (
   "ORDER_ID"   number,
   "PRINT_TYPE" varchar2(10 byte) not null enable,
   "QTY"        number(5,0) not null enable,
   "PAPER_SIZE" varchar2(10 byte) not null enable,
   "PAPER_TYPE" varchar2(20 byte) not null enable,
   "FILE_PATH"  varchar2(225 byte) not null enable
)
segment creation immediate
pctfree 10
pctused 40
initrans 1
maxtrans 255 nocompress
logging
tablespace "USERS";

alter table "PRINT"
   add primary key ( "ORDER_ID" )
      using index tablespace "USERS" enable;
alter table "PRINT"
   add constraint "FK_PRINT_ORDER"
      foreign key ( "ORDER_ID" )
         references "Order" ( "ID" )
      enable;



create table "INVOICE" (
   "ORDER_ID"     number not null enable,
   "INVOICE_DATE" varchar2(10 byte) not null enable,
   "NET_AMOUNT"   number not null enable
)
segment creation immediate
pctfree 10
pctused 40
initrans 1
maxtrans 255 nocompress
logging
tablespace "USERS";

alter table "INVOICE"
   add constraint "PK_INVOICE_ORDER" primary key ( "ORDER_ID" )
      using index tablespace "USERS" enable;
alter table "INVOICE"
   add constraint "FK_INVOICE_ORDER"
      foreign key ( "ORDER_ID" )
         references "Order" ( "ID" )
      enable;



create table "PAYMENT" (
   "PAYMENT_NUMBER" number,
   "INVOICE_ID"     number,
   "AMOUNT"         number not null enable,
   "METHOD"         varchar2(20 byte) not null enable,
   "REFERENCE_NO"   varchar2(10 byte),
   "PAYMENT_AT"     timestamp(6) not null enable
)
segment creation immediate
pctfree 10
pctused 40
initrans 1
maxtrans 255 nocompress
logging
tablespace "USERS";

alter table "PAYMENT"
   add constraint "PK_PAYMENT"
      primary key ( "PAYMENT_NUMBER",
                    "INVOICE_ID" )
         using index tablespace "USERS" enable;
alter table "PAYMENT" add unique ( "REFERENCE_NO" )
   using index tablespace "USERS" enable;
alter table "PAYMENT"
   add constraint "FK_PAYMENT_INVOICE"
      foreign key ( "INVOICE_ID" )
         references "INVOICE" ( "ORDER_ID" )
      enable;